name: courtrankrl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.13
  - pip
  - pip:
    - numpy
    - pandas
    - tqdm
    - torch
    - transformers>=4.44.0
    - sentence-transformers>=3.0.0
    - faiss-cpu
    - pyarrow
    - scikit-learn
    - networkx
    - python-docx
    - striprtf
    - python-dotenv
    - jupyter
    - ipykernel
    - gymnasium
    - matplotlib
    - seaborn
    - beautifulsoup4 